### ISSUE TITLE
Default locale to None

### ISSUE THREAD

**Issue by ghost** [goavki/apertium-apy#27]
In in `ListLanguageNamesHandler` in servlet.py should we change the `localeArg = self.get_argument('locale')` to be like `localeArg = self.get_argument('locale', default=None)`? Without the defaulting to None, I don't see why the code `elif 'Accept-Language' in self.request.headers:` is useful (in order to use the header field there still needs to be the "locale" parameter but with no value).

**Comment by simonnarang** [comment]
I am working on this for GCI

**Comment by simonnarang** [comment]
Done

**Comment by Putti** [comment]
@simonnarang should we change it so? That's the question.

**Comment by Androbin** [comment]
@ghost Shall we close this now?
