### ISSUE TITLE
formatter param to /translate

### ISSUE THREAD

**Issue by unhammer** [goavki/apertium-apy#33]
e.g. to specify rehtml vs rehtml-noent

**Comment by shardulc** [comment]
Can I implement this as part of a GCI task? (https://codein.withgoogle.com/dashboard/task-instances/5435330322759680/)

**Comment by sushain97** [comment]
Yes.

**Comment by unhammer** [comment]
wait this is already implemented in a branch

**Comment by unhammer** [comment]
Could you move your lines 415..427 into a function like `self.getFormat` which returns the pair `(deformat, reformat)`?

**Comment by shardulc** [comment]
"This is already implemented in master": I'm sorry, what do you mean?
"Could you move your lines ...": done (same PR).

**Comment by unhammer** [comment]
> "This is already implemented in master": I'm sorry, what do you mean?

I wrote this issue before implementing the stuff in
41baa29fc16f9f81a533ed27446547fdcb159217 (and forgot to link the issue
and commit).

> "Could you move your lines ...": done (same PR).

Cool, looks mergable :)

**Comment by unhammer** [comment]
right :)
