### ISSUE TITLE
langnames calls should be non-blocking

### ISSUE THREAD

**Issue by unhammer** [goavki/apertium-apy#34]
if getLocalizedLanguages reads from a damaged disk/db, it can block other requests. It should use the same non-blocking yield pattern as translation does.

**Comment by Androbin** [comment]
@unhammer Which line(s) would get stuck exactly?

**Comment by unhammer** [comment]
In `ListLanguageNamesHandler`, something like

`self.sendResponse(getLocalizedLanguages(localeArg, self.langNames, languages=languagesArg.split(' ')))` 

where `getLocalizedLanguages` might take a lot of time will block all of Apy until `getLocalizedLanguages` has returned. 

Compare with `AnalyzeHandler` which does 
```
            result = yield translation.translateSimple(in_text, commands)
            self.sendResponse(self.postproc_text(in_text, result))
```

where `translateSimple` is also a `@gen.coroutine`.
