### ISSUE TITLE
Document translation limits

### ISSUE THREAD

**Issue by sushain97** [goavki/apertium-apy#40]
@unhammer:

> We might want to have some locks or a similar method of ensuring we don't start more than N processes at a time (not likely to happen in normal usage, more to protect against malicious users), could have a dict of doc_locks just like pipeline_locks.

migrated from https://sourceforge.net/p/apertium/tickets/7/

**Comment by jatinluthra14** [comment]
https://github.com/goavki/apertium-apy/pull/46

**Comment by unhammer** [comment]
@sushain97 I mentioned on irc, we don't need a per-pair list of semaphores. Since we don't keep pipe-processes around when doing doc translation, there's no need to differentiate between them here. So just one global semaphore with however many pipelines we can stomach.

**Comment by sushain97** [comment]
Ah! Sounds good. This must have slipped my mind :)
