### ISSUE TITLE
Document translation should spawn processes

### ISSUE THREAD

**Issue by sushain97** [goavki/apertium-apy#41]
@unhammer:

> We probably shouldn't do threading since it makes python eat all our swap :-) It should be simple enough to start the process using tornado.process.Subprocess in a @gen.coroutine using "yield", similar to translateSimple()

migrated from https://sourceforge.net/p/apertium/tickets/7/

**Comment by jatinluthra14** [comment]
I'd like to work on this as a GCI task

**Comment by sushain97** [comment]
There is already a task for this :) Search for APy.

**Comment by jatinluthra14** [comment]
https://github.com/goavki/apertium-apy/pull/45

**Comment by unhammer** [comment]
@jatinluthra14 can you explain what this fixes?

**Comment by jatinluthra14** [comment]
Yes, it uses subprocess to yield processes for translation

**Comment by unhammer** [comment]
(see comments on the pull)

**Comment by unhammer** [comment]
Closed in  dd926c9
