### ISSUE TITLE
Use config file instead of long command line arguments

### ISSUE THREAD

**Issue by svineet** [goavki/apertium-apy#5]
An argument like `--config=config.conf` would be great, the commands become really long with all the settings.

**Comment by unhammer** [comment]
re: https://github.com/goavki/apertium-html-tools/pull/35#issuecomment-169465753 if there's a conf file, I'd prefer if it accepted all the switches. But if a switch is given explicitly, it overrides any conf file setting.

**Comment by jonorthwash** [comment]
It seems that currently both are being accepted, per https://github.com/goavki/apertium-html-tools/pull/35#issuecomment-169306972 ?  Or is the referenced `config.conf` the one for html-tools?

**Comment by svineet** [comment]
No, the config file is for html tools, so that it can know the site key.
The site key is the public secret for recaptcha used to render the widget.
There is no config file option for apy, instead command line options for
wiki credentials and the recaptcha secret used to verify users.

**Comment by jonorthwash** [comment]
Ah, that seems reasonable then.  Could you then clarify your comment from before, to make it clear that it's `config.conf` for html-tools?

**Comment by jonorthwash** [comment]
Current status of this issue: PR #7 needs to have conflicts resolved and be merged.

**Comment by Androbin** [comment]
Is this issue still up-to-date?

**Comment by jonorthwash** [comment]
I think so, but you could probably check :)
