### ISSUE TITLE
perWord example on Html-tools (and on wiki) fails with bad request error

### ISSUE THREAD

**Issue by share-with-me** [goavki/apertium-apy#63]
![screenshot from 2017-08-24 18-27-54](https://user-images.githubusercontent.com/8894636/29667437-efefdf30-88cb-11e7-81cf-c30f81cad8d1.png)

**Comment by share-with-me** [comment]
I replaced `en-es` with `eng-spa` and it worked. I am not sure if that is the right way to go about it.

![screenshot from 2017-08-24 18-29-27](https://user-images.githubusercontent.com/8894636/29667503-2a717ef2-88cc-11e7-8e3f-fbd535e3780a.png)

**Comment by sushain97** [comment]
Yeah, I believe the newer endpoints only support iso639-3 codes on purpose.
