### ISSUE TITLE
calcCoverage example on wiki page fails

### ISSUE THREAD

**Issue by share-with-me** [goavki/apertium-apy#64]
- `getCoverage` may have to be replaced with `calcCoverage`

![screenshot from 2017-08-29 23-09-27](https://user-images.githubusercontent.com/8894636/29835280-09fb0116-8ce1-11e7-8cf8-b6eceaabf3f3.png)

- the example on wiki page fails with `400- bad request` error.

![screenshot from 2017-08-29 23-10-15](https://user-images.githubusercontent.com/8894636/29835345-3e433b28-8ce1-11e7-9b59-56d2cee9075e.png)

**Comment by share-with-me** [comment]
Again, replacing `en-es` with `eng-spa` gives the output.

![screenshot from 2017-08-29 23-10-35](https://user-images.githubusercontent.com/8894636/29835409-6d239550-8ce1-11e7-9c62-45bf0ce3a660.png)

**Comment by sushain97** [comment]
It may be that we just don't support ISO 639-3 codes on this newer endpoints.

**Comment by share-with-me** [comment]
Ohh. I also observed this for `/perWord` handler.
