### ISSUE TITLE
Analyze and Generate methods fail on APy URL server

### ISSUE THREAD

**Issue by share-with-me** [goavki/apertium-apy#65]
I tried with 2 requests through APy sandbox. Both of them work in localhost while both of them fail when the server is `https://www.apertium.org/apy` with `400 - Bad request error`. Is it because APy is running some other version of code on the server?

**Fails on APy URL**

![screenshot from 2017-08-31 21-00-31](https://user-images.githubusercontent.com/8894636/29932240-45e44bf0-8e63-11e7-8ecd-6baf21cd22ca.png)

![screenshot from 2017-08-31 21-20-11](https://user-images.githubusercontent.com/8894636/29932555-2050cb10-8e64-11e7-93f8-8596bf4185aa.png)

**Works on localhost**
![screenshot from 2017-08-31 21-27-29](https://user-images.githubusercontent.com/8894636/29932881-1e68a286-8e65-11e7-9c7a-953511996953.png)

**Comment by sushain97** [comment]
This really isn't a problem with the APy code. Generation and analysis is
probably disabled or something on the apertium.org API instance. If it
works locally, it doesn't belong here as an issue (generally).
