### ISSUE TITLE
apy / identifyLang returns code 400

### ISSUE THREAD

**Issue by Androbin** [goavki/apertium-apy#70]
Requests to https://www.apertium.orf/apy/identifyLang produce code 400 errors.

![screenshot](https://user-images.githubusercontent.com/16437156/34388874-8c768274-eb36-11e7-86a6-3fa65eced2ef.png)

**Comment by sushain97** [comment]
Hm, I wonder if this is bad request (400) because of no text. Might be. In that case it's not a bug here and is one over in html-tools but for a slightly different reason (shouldn't allow).

**Comment by Androbin** [comment]
Just tested it, you're right.

**Comment by sushain97** [comment]
Cool. Would appreciate it if you could open a new issue over there :) Good catch.
