### ISSUE TITLE
End Python 3.2 support (must cut a release + modify changelog)

### ISSUE THREAD

**Issue by sushain97** [goavki/apertium-apy#73]
Python 3.2's flake and mypy malfunction. This makes our build process and imports somewhat nasty (introduced in https://github.com/goavki/apertium-apy/pull/69).

Should we stop supporting Py3.2?

cc @unhammer

**Comment by unhammer** [comment]
What currently supported distros use py3.2?

Also, perhaps Apy is feature-complete enough that we could make a release that's the last one supporting 3.2, bump a major version number and from then on only support 3.3 and higher.

**Comment by sushain97** [comment]
> What currently supported distros use py3.2?

sushain: TinoDidriksen: “What currently supported distros use py3.2?” any ideas how to find this quickly?
[09:25am] sushain: context is APy
[09:25am] TinoDidriksen: None
[09:25am] sushain: perfect

> Also, perhaps Apy is feature-complete enough that we could make a release now, calling it The last one supporting 3.2, bump a major version number and from then on only support 3.3 and higher.

I concur. Switching around the metadata of this issue.

cc @Androbin

**Comment by Androbin** [comment]
@sushain97 Ping me when it's okay to remove. Then I can clean up the leftover pieces.

**Comment by sushain97** [comment]
It's okay now. The PR would make the changes and update the changelog with
changes since last release including v3.2 deprecation notice. Then, I would
tag the current master and merge your PR.
