### ISSUE TITLE
Debian package doesn't bring streamparser module

### ISSUE THREAD

**Issue by danielmartinez** [goavki/apertium-apy#83]
Hi all,

I was trying to install apertium-apy from nightly debian repo at apertium.projectjj.com, it installs, but when you try to start service it shows:

Feb 06 11:31:26 softaragones python3[8195]: Traceback (most recent call last):
Feb 06 11:31:26 softaragones python3[8195]: File "servlet.py", line 58, in <module>
Feb 06 11:31:26 softaragones python3[8195]: from streamparser.streamparser import parse, known
Feb 06 11:31:26 softaragones python3[8195]: ImportError: No module named 'streamparser'
Feb 06 11:31:26 softaragones systemd[1]: apertium-apy.service: main process exited, code=exited, status=1/FAILURE
Feb 06 11:31:26 softaragones systemd[1]: Unit apertium-apy.service entered failed state.
Feb 06 11:31:26 softaragones systemd[1]: apertium-apy.service holdoff time over, scheduling restart.
Feb 06 11:31:26 softaragones systemd[1]: Stopping Translation server and API for Apertium...
Feb 06 11:31:26 softaragones systemd[1]: Starting Translation server and API for Apertium...
Feb 06 11:31:26 softaragones systemd[1]: apertium-apy.service start request repeated too quickly, refusing to start.
Feb 06 11:31:26 softaragones systemd[1]: Failed to start Translation server and API for Apertium.
Feb 06 11:31:26 softaragones systemd[1]: Unit apertium-apy.service entered failed state.

In order to workaround that, I downloaded streamparser from https://github.com/goavki/streamparser/tree/cf67427283a5316f3a23dbc193e75603c5cbe34c and put at /usr/share/apertium-apy/ directory, after that, it seems to be started and running OK, so I supose this module is missing inside debian package an it should to be included.

Bye!

**Comment by sushain97** [comment]
I think @TinoDidriksen said he would be taking care of this

**Comment by TinoDidriksen** [comment]
Yup, tracked in https://github.com/TinoDidriksen/apertium-packaging/issues/2

**Comment by TinoDidriksen** [comment]
Fixed the submodule issue, but APy doesn't have an installer.

I've added the files to https://github.com/TinoDidriksen/apertium-packaging/blob/master/trunk/apertium-apy/debian/apertium-apy.install which I guess is all that's needed, but an actual installer would be nice.

**Comment by sushain97** [comment]
Do you mind opening an issue for that? I'm not exactly sure what an installer means in this context.
